version: '3.8'

networks:
  app-network:
    driver: bridge
volumes:
  cache:
    driver: local
services:
  # Infrastructure
  redis:
    image: redis:7.2.4-alpine
    restart: always
    container_name: redis
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 30s
      retries: 3
    command: redis-server --save 20 1 --loglevel warning --requirepass 128391893012908983ddd
    volumes:
      - cache:/data
    ports:
      - "6379:6379"
    networks:
      app-network:

  grafana:
    container_name: grafana
    build: './config/grafana'
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      app-network:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      app-network:

  app:
    env_file:
      - .env.local
    container_name: app
    image: virginonline/waliot
    build:
      context: .
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - app-network
