spring:
  application:
    name: waliot
  cache:
    type: redis
    cache-names: location
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PASSWORD}
  main:
    banner-mode: off
yandex:
  url: https://geocode-maps.yandex.ru/1.x/
  key: ${YANDEX_API_KEY}
