spring:
  config:
    import: optional:file:.env.local[.properties]
  application:
    name: waliot
  cache:
    type: redis
    redis:
      enable-statistics: true
    cache-names: location
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PASSWORD}
  main:
    banner-mode: off
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true

yandex:
  url: https://geocode-maps.yandex.ru/1.x/
  key: ${YANDEX_API_KEY}
